Run ci actions for multiple python versions

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -9,40 +9,48 @@ jobs:
   build:
 
     runs-on: ubuntu-latest
-
+    strategy:
+      max-parallel: 3
+      fail-fast: false
+      matrix:
+        python-version: ['3.6', '3.7', '3.8'] # 3.9 build currently failing
+    name: Build for python ${{ matrix.python-version }}
     steps:
     - uses: actions/checkout@v2
-
-    - name: Set up Python 3.6
+    - name: Set up python ${{ matrix.python-version }}
       uses: actions/setup-python@v2
       with:
-        python-version: '3.6'
-
+        python-version: ${{ matrix.python-version }}
+        architecture: x64
     - name: Cache Dependencies
       id: cache
       uses: actions/cache@v2
       with:
-        # This path is specific to Ubuntu
-        path: ~/.cache/pip
-        # Look to see if there is a cache hit for the corresponding requirements file
-        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
-        restore-keys: |
-          ${{ runner.os }}-pip-
-          ${{ runner.os }}-
+        # os independent path
+        path: ${{ env.pythonLocation }}
+        # Look to see if there is a cache hit for the corresponding python location and requirements file
+        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
 
     - name: Install Dependencies
       run: |
-        python -m pip install --upgrade pip
-        pip install flake8 pytest
-        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+        # we need to build proper wheel for scikit-learn 0.19.2 on python 3.8
+        # cacheless run will be slow, but next ones will use wheel
+        # if we skip wheel build - scikit-learn will be build from source each time
+        # if is as slow as initial wheel build up but for every run
+        python -m pip install --upgrade pip setuptools wheel
+        python -m pip install numpy==1.17.5 # scipy need numpy on wheel build step, using same from requirements.txt
+        python -m pip install scipy==1.2.3 # scikit-learn need numpy and scipy on wheel build step, using same from requirements.txt
+        python -m pip install flake8 pytest # test and linting dependencies
+        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
 
     - name: Linting with flake8
       run: |
         # stop the build if there are Python syntax errors or undefined names
-        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || exit 1
+        flake8 . --select=E9,F63,F7,F82 --show-source || exit 1
         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
+        echo "================================ Lint warnings =============================="
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
 
     - name: Test with pytest
       run: |
-        python -m pytest
+        pytest
